### ISSUE TITLE
Possible bug related to functor

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/pyTuplingUtils#5]
Yesterday I assumed that the `GT` functor bug you described was due to the fact that `GT` returns a single Boolean, not an array of Booleans.

However, I tried the following code:
```
import numpy as np

True & np.array([1,0,0,1,1])
```

And the output is what we expect, so in principle, the old `GT` functor works.

@manuelfs Can you post the error message when trying to use the `GT` functor?

**Comment by manuelfs** [comment]
Defining `'GTBAD': lambda x, y:  True if x > y else False` and calling `GTBAD(Kplus_PT, 2000)` I get

```
|00:06:27|~/code/lhcb-ntuples-gen$ ./utils/cutflow_output_yml_gen_pre_0.9.0.py ntuples/pre-0.9.0/Dst-cutflow_mc/Dst--20_03_18--cutflow_mc--cocktail--2016--md.root run2-b2D0MuXB2DMuForTauMuLine/cutflow/input-run2.yml gen/cutflow/output-run2.yml run2 -t 'TupleB0/DecayTree'
Traceback (most recent call last):
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 66, in _call_userfunc
    return f.visit_wrapper(f, tree.data, children, tree.meta)
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 345, in _vargs_inline
    return f(*children)
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 329, in f
    return _f(self, *args, **kwargs)
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyTuplingUtils-0.0.1-py3.8.egg/pyTuplingUtils/boolean/eval.py", line 127, in func_call
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyTuplingUtils-0.0.1-py3.8.egg/pyTuplingUtils/boolean/const.py", line 34, in <lambda>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./utils/cutflow_output_yml_gen_pre_0.9.0.py", line 116, in <module>
    result_addon = CutflowGen(
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyTuplingUtils-0.0.1-py3.8.egg/pyTuplingUtils/cutflow.py", line 66, in do
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyTuplingUtils-0.0.1-py3.8.egg/pyTuplingUtils/boolean/eval.py", line 150, in eval
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 105, in transform
    return self._transform_tree(tree)
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 102, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/lark_parser-0.8.9-py3.8.egg/lark/visitors.py", line 72, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "func_call":

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by yipengsun** [comment]
I think I know why: Considering `GTBAD(Kplus_PT, 2000)`:

1. First, `Kplus_PT > 2000` would return an array of boolean: `[True, False, False, ... ]`
2. Then the `True if ... else False` will evaluate
3. Since the comparison returns an array, _The truth value of an array with more than one element is ambiguous._

**Comment by yipengsun** [comment]
And my "fix" _does fix_ the problem. I think we can safely close this.
